import { Toaster } from "@/presentation/components/ui/sonner";
import { getAuthTokens } from "@/utils/getAuthTokens";
import { tokensToUserEntity } from "@/utils/tokensToUserEntity";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../presentation/styles/globals.css";
import { Providers } from "./providers";

type RootLayoutProps = Readonly<{
  children: React.ReactNode;
}>;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({ children }: RootLayoutProps) => {
  const tokens = await getAuthTokens();
  const user = tokens ? tokensToUserEntity(tokens.decodedToken) : null;
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers user={user}>{children}</Providers>
        <Toaster />
      </body>
    </html>
  );
};

export default RootLayout;
